.\" ============================================================================
.TH PBB 1 2022-09-09
.\" ============================================================================
.SH NAME
pbb \- Pandoc Bash Blog
.\" ============================================================================
.SH SYNOPSIS
.B pbb init
.I TITLE
.br
.B pbb title
.I TITLE
.br
.B pbb enable
.I FEATURE
.br
.B pbb disable
.I FEATURE
.br
.B pbb gccode
.I CODE
.br
.B pbb build
.br
.B pbb serve
.br
.B pbb deploy
.br
.B pbb help
.\" ============================================================================
.SH DESCRIPTION
.B pbb
builds and deploys static HTML files from Markdown source.
It is meant to be run in a Git repository published via GitHub Pages, using the
.I docs
directory of the default branch as the publishing source.
.SS Subcommands
.TP
.BI init\  TITLE
Initialize a new blog with title
.I TITLE
in an empty Git repository.
This creates the
.IR docs ,
.IR includes ,
.IR images ,
and
.I assets
directories.
It drops a
.I .nojekyll
file into the
.I docs
directory to prevent the default GitHub Actions workflow from running Jekyll.
It symlinks the style sheet and the calendar icon into the
.I assets
directory, creates the header files to be used on every page in the
.I includes
directory, generates the
.I .metadata.yml
file, and creates an example post with the current date.
.RS
.PP
Unquoted whitespace in
.I TITLE
gets squeezed.
.RE
.TP
.BI title\  TITLE
Change the blog title to
.IR TITLE .
Unquoted whitespace gets squeezed.
.TP
.BI enable\  FEATURE
.PD 0
.TP
.BI disable\  FEATURE
.PD
Turn
.I FEATURE
on/off.
The corresponding feature is stored in
.I .pbbconfig
with a value of
.I on
or
.IR off .
Available features are
.I math
and
.IR bibliography .
See
.B OPTIONS
for details.
.TP
.BI gccode\  CODE
Include a snippet with tracking code for GoatCounter on each page, where
.I CODE
is the code that identifies where you access your GoatCounter account, as in
.UR https://CODE.goatcounter.com
.UE .
.RS
.PP
To disable GoatCounter, set the code to the empty string using
.BR pbb\ gccode\ '' .
.RE
.TP
.B build
Build HTML pages from the provided Markdown input. The output is stored in the
.I docs
directory, which gets cleaned first.
The
.I images
directory is copied into
.IR docs ,
and if a favicon input file exists, the favicon is generated (see
.BR FILES ).
Within the
.I docs
directory, a subdirectory
.I diagrams
is created to hold graphs generated by dot (see
.BR OPTIONS ).
.RS
.PP
To be processed, a Markdown file has to have a name like
.IR YYYY-MM-DD-post-title.md ;
all these files become separate posts, and a file
.I index.md
containing links to all posts is generated to serve as the front page.
.RE
.TP
.B serve
Serve the blog locally at
.UR http://localhost:8000
.UE
to preview.
As long as this is running, changes to Markdown files immediately trigger a
rebuild of the corresponding HTML file, and changes to files in the
.I images
directory trigger a fresh copy of that file into the
.I docs/images
directory, allowing to quickly rebuild a post while working on it and previewing
it in a browser. This is implemented using
.BR inotifywait (1).
.TP
.B deploy
Publish the blog via GitHub Pages.
This commits all changes in the
.I artifacts
directory and pushes to the configured remote.
.\" ============================================================================
.SH OPTIONS
.SS Table of contents
To generate a table of contents for a post, start the Markdown file with this
YAML header:
.PP
.in +4n
.EX
\-\-\-
toc: true
\&...
.EE
.in
.PP
There should be only one level-one heading in the file, and no heading level
should be skipped.
The heading for the table of contents defaults to \*(lqTable of contents\*(rq
and can be ajdusted by modifing the value of
.I toc-title
in
.IR .metadata.yml .
.SS MathJax
When the feature
.I math
is enabled, inline (between pairs of
.IR $ )
and display (between pairs of
.IR $$ )
math is rendered using MathJax instead of just Unicode characters.
.SS Bibliography
When the
.I bibliography
feature is enabled, the
.I --citeproc
opion is added to the pandoc invocation, which builds a bibliography and enables
citations.
See the
.UR https://pandoc.org/MANUAL.html#citations
pandoc documentation
.UE
for details regarding the format and location of the bibliography as well as how
citations work.
.PP
The heading of the bibliography defaults to \*(lqBibliography\*(rq and can be
adjusted by modifying the value of
.I reference-section-title
in
.IR .metadata.yml .
.SS dot graphs
When a code block has the class
.IR dot ,
its contents are piped through Graphviz
.I dot
and the code block is replaced by the generated graph in SVG format.
To add a caption, an attribute
.I caption
can be used, and to add the original code block as an HTML comment, the class
.I includeCode
(or
.IR include-source )
can be added.
.PP
.in +4n
.EX
``` {.dot .includeSource caption="A dot graph"}
digraph G {
    a -> b
}
```
.EE
.\" ============================================================================
.SH FILES
.TP
.I .pbbconfig
Stores configuration settings for the blog such as the blog title and the
GoatCounter code.
It should never have to be edited manually; instead, commands such as
.B pbb title
and
.B pbb gccode
are used to modify its contents.
.TP
.I .metadata.yml
Stores metadata used by pandoc such as the heading for the table of contents,
the field that controls generation of the table of contents (which can be
overridden per post, see
.BR OPTIONS ),
and the heading for the bibliography.
.TP
.I assets
Contains various assets used when the blog is built:
.RS
.TP
.I favicon.*
If exactly one image file matching this pattern exists, it is converted to a
32x32 PNG image and used as the favicon by
.BR pbb\ build .
If the image is not square, a square is placed in its centre and everything
outside the square is cropped.
If the file is an animated GIF, the first frame is used.
.TP
.I pbb.css
The style sheet used by Pandoc Bash Blog; it is symlinked from
.I $XDG_DATA_HOME/pbb/pbb.css
and updated there when
.B pbb
is updated.
.TP
.I calendar.svg
This is an icon used to decorate datestamps on posts; it is symlinked from
.IR $XDG_DATA_HOME/pbb/calendar.svg .
.RE
.TP
.I includes
Contains files containing HTML snippets to be included when converting the
Markdown files:
.RS
.TP
.I header.html
The page header for each post with a link back to the index page.
.TP
.I fontlinks.html
The header links to get the Google Fonts CSS snippets for the fonts used.
.TP
.I favicon.html
The favicon link that gets included if a favicon has been generated.
.TP
.I goatcounter.html
A script snippet that goes at the end of the
.I <body>
tag if a GoatCounter code has been set.
.RE
.TP
.I $XDG_DATA_HOME/bash-completion/completions/pbb
The tab completion for
.BR pbb .
.TP
.I $XDG_DATA_HOME/man/man1/pbb.1
The source for this man page.
.TP
.I $XDG_DATA_HOME/pandoc/filters/dotgraph.lua
The Lua filter used to generate Dot graphs from special code blocks.
.TP
.I $XDG_DATA_HOME/pandoc/solarizeddark.theme
The syntax highlighting theme used for code blocks.
.\" ============================================================================
.SH NOTES
The source code for
.B pbb
is on
.UR https://github.com/bewuethr/pandoc-bash-blog
GitHub
.UE .
Development is chronicled at
.UR https://benjaminwuethrich.dev
.UE .
.\" ============================================================================
.SH BUGS
There is currently no way to control the order of posts having the same date
other than carefully selecting the filename so the more recent post is sorted
after the older post.
.\" ============================================================================
.SH EXAMPLE
Initialize a new blog with title \*(lqMy blog\*(rq in an empty Git repository:
.PP
.in +4n
.EX
git init
pbb init 'My blog'
.EE
.in
.PP
To change the title later on, use
.PP
.in +4n
.EX
pbb title 'My blog with a new title'
.EE
.in
.PP
.B pbb init
has generated an example post,
.I 2020-04-13-my-first-post.md
(with the correct date, of course), which contains
.PP
.in +4n
.EX
# My first post

Hello world!
.EE
.in
.PP
Edit that post to your liking using pandoc Markdown; images go into the
.I images
directory.
To include a dot graph, create a code block with class
.I dot
and it wil be replaced with the graph in the output.
If you want a table of contents for a post, insert a YAML document at the top
which sets the
.I toc
variable to
.I true
(see
.BR OPTIONS ).
.PP
To get a favicon, place a picture at
.IR assets/favicon.png ,
where the file type can by any image type, as long as ImageMagick understands
it.
.PP
To add a GoatCounter tracking code, say,
.IR CODE ,
run
.BR pbb\ gccode\ CODE .
.PP
To enable MathJax, run
.BR pbb\ enable\ math ,
and if you want a bibliography and citations, run
.BR pbb\ enable\ bibliography .
.PP
Build your blog with
.B pbb build
and run
.B pbb serve
to inspect the result locally at
.UR http://localhost:8000
.UE .
.PP
When you're good to publish your blog, run
.BR pbb\ deploy .
You maybe have to set the Git remote first with something like
.PP
.in +4n
.EX
git remote add origin https://github.com/<yourname>/<repo-name>.git
.EE
.in
.PP
Managing version control of the files in the default branch is completely up
you.
.\" ============================================================================
.SH SEE ALSO
.BR dot (1),\  imagemagick (1),\  inotifywait (1),\  pandoc (1)
.\" ============================================================================
