# See https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# Require ATX-style headers
MD003: atx

# Require dashes for unordered lists
MD004: dash

# Allow exactly 2 trailing spaces, but only if they cause a line break
MD009:
  strict: true

# Enforce line length, but not in code blocks and tables
MD013:
  code_blocks: false
  tables: false

# Allow identical titles only if they aren't siblings
MD024:
  siblings_only: true

# Allow headings to end in question marks
MD026:
  punctuation: .,;:!。，；：！

# Require ordered list prefixes 1., 2., 3., ...
MD029:
  style: ordered

# Allow some inline HTML elements
MD033:
  allowed_elements:
    - details
    - summary

# Require "---" for horizontal rules
MD035:
  style: ---

# Require fenced code blocks
MD046:
  style: fenced
