name: Lint code base

on:
  push:

jobs:
  build:
    name: Lint code base
    runs-on: ubuntu-18.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2.3.3
        with:
          fetch-depth: 0
      - name: Lint code base
        uses: github/super-linter@v3.12.0
        env:
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true
          VALIDATE_CSS: true
          VALIDATE_JSON: true
